<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                exclude-result-prefixes="xhtml sitemap">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap - TijaraHub Services</title>
        <style type="text/css">
          body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            color: #333;
            background: #f9f9f9;
            margin: 0;
            padding: 20px;
          }
          h1 {
            margin: 0 0 20px 0;
            font-size: 24px;
            color: #252B58;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
          }
          th {
            background: #252B58;
            color: #fff;
            padding: 10px;
            text-align: left;
          }
          td {
            border-bottom: 1px solid #eee;
            padding: 10px;
          }
          a {
            color: #F18A5F;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
        </style>
      </head>
      <body>
        <h1>XML Sitemap - TijaraHub Services</h1>
        <xsl:variable name="total" select="count(sitemap:urlset/sitemap:url)"/>
        <p>Total URLs: <xsl:value-of select="$total"/></p>
        <table>
          <tr>
            <th>URL</th>
            <th>Last Modified</th>
            <th>Change Frequency</th>
            <th>Priority</th>
            <th>Alternate Languages</th>
          </tr>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
              <td><xsl:value-of select="sitemap:lastmod"/></td>
              <td><xsl:value-of select="sitemap:changefreq"/></td>
              <td><xsl:value-of select="sitemap:priority"/></td>
              <td>
                <xsl:for-each select="xhtml:link">
                  <xsl:if test="@rel='alternate'">
                    <xsl:value-of select="@hreflang"/>: 
                    <a href="{@href}"><xsl:value-of select="@href"/></a>
                    <br/>
                  </xsl:if>
                </xsl:for-each>
              </td>
            </tr>
          </xsl:for-each>
        </table>
        <p style="margin-top: 20px; font-size: 12px; color: #999;">
          Generated by TijaraHub Services - 
          <a href="https://services.tijarahub.com/">https://services.tijarahub.com/</a>
        </p>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>